name = "marceau"
version = "1.2.0"
description = "A MIME types library for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "marceau" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_stdlib = "~> 0.31"
